version: "3.9"

services:
  ctf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-ctf
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

