version: '3.8'

services:
  treasuremap:
    image: treasuremap
    build:
      context: ./Challenge
    restart: unless-stopped
    container_name: treasuremap
    ports:
      - "1337:80"
    pids_limit: 50  
    ulimits:
      nproc: 50 
      nofile:
        soft: 100
        hard: 200
    cap_drop:
      - ALL 
    read_only: true 
    tmpfs:
      - /tmp:size=10M,noexec,nodev,nosuid 
    healthcheck:
      test: ["CMD-SHELL", "sleep 120 && exit 1"] 
      interval: 2m
      timeout: 10s
      retries: 1
      start_period: 10s