version: '3.8'

services:
  ctfchallenge:
    build:
      context: .  
      dockerfile: Dockerfile           
    container_name: 69_cores_baby                    
    restart: always
    cap_add:                           
      - CHOWN                          
      - DAC_OVERRIDE                   
    cap_drop:                          
      - ALL
    ports:
      - "5000:5000"      
